name: realm-panel
services:
  realm-panel-core:
    image: realm-panel-core:${RMP_VERSION:-0.9.3}
    container_name: realm-panel-core
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data/realm:/app/data/realm:ro
      - ./data/run:/app/data/run
    read_only: true
    tmpfs: [/tmp]
    cap_drop: [ALL]
    cap_add: [NET_BIND_SERVICE]
    security_opt: [no-new-privileges:true]
    environment:
      TZ: Asia/Shanghai
    logging:
      driver: json-file
      options: {max-size: "5m", max-file: "3"}
  realm-panel-web:
    image: realm-panel-web:${RMP_VERSION:-0.9.3}
    container_name: realm-panel-web
    restart: unless-stopped
    network_mode: host
    depends_on: [realm-panel-core]
    volumes:
      - ./data:/app/data
    read_only: true
    tmpfs: [/tmp]
    cap_drop: [ALL]
    security_opt: [no-new-privileges:true]
    environment:
      TZ: Asia/Shanghai
    logging:
      driver: json-file
      options: {max-size: "5m", max-file: "3"}
