<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue'
import { LayoutDashboard, ArrowLeftRight, Layers, FileInput, Archive, ScrollText, Activity, Settings, Command, Plus, Menu, LogOut, RefreshCw, Search, ShieldCheck, Sun, Moon } from 'lucide-vue-next'
import { api, base, setCsrf } from './api'
import RuleEditor from './RuleEditor.vue'
const confirm = window.confirm.bind(window)
type Row = Record<string, any>
const pages = [{ name: '概览', icon: LayoutDashboard }, { name: '转发规则', icon: ArrowLeftRight }, { name: '批量操作', icon: Layers }, { name: '导入 / 导出', icon: FileInput }, { name: '备份', icon: Archive }, { name: '运行日志', icon: ScrollText }, { name: '操作日志', icon: ScrollText }, { name: '系统状态', icon: Activity }, { name: '设置', icon: Settings }]
const page = ref('概览'), authenticated = ref(false), ready = ref(false), busy = ref(false), mobile = ref(false), toast = ref(''), error = ref(false)
const username = ref(''), password = ref(''), status = ref<Row>({}), rules = ref<Row[]>([]), groups = ref<string[]>([]), backups = ref<Row[]>([]), logs = ref<any[]>([]), settings = ref<Row>({ network: {}, whitelist: [] })
const selected = ref<number[]>([]), query = ref(''), groupFilter = ref(''), editor = ref<Row | null>(null), editingId = ref<number | null>(null)
const content = ref(''), kind = ref('json'), preview = ref<Row | null>(null), strategy = ref('skip'), groupName = ref(''), batchGroup = ref('默认')
const theme = ref(localStorage.getItem('rmp-theme') || 'system'), whitelist = ref(''), lineCount = ref(100), autoRefresh = ref(false)
const currentPassword = ref(''), newPassword = ref(''), confirmPassword = ref('')
const sessionExpired = () => { authenticated.value = false; editor.value = null }
window.addEventListener('rmp-session-expired', sessionExpired)
function toggleTheme() { theme.value = (theme.value === 'dark' || (theme.value === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches)) ? 'light' : 'dark' }
let timer: ReturnType<typeof setInterval>, toastTimer: ReturnType<typeof setTimeout>
watch(theme, value => { document.documentElement.dataset.theme = value; localStorage.setItem('rmp-theme', value) }, { immediate: true })
watch(page, () => { mobile.value = false; refresh().catch(showError) })
watch([lineCount, autoRefresh], () => refresh().catch(showError))
function notify(message: string, bad = false) { toast.value = message; error.value = bad; clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.value = '', 7000) }
function showError(e: unknown) { notify(e instanceof Error ? e.message : String(e), true) }
async function action(fn: () => Promise<void>, message = '操作成功') { if (busy.value) return; busy.value = true; try { await fn(); await refresh(); notify(message) } catch (e) { showError(e) } finally { busy.value = false } }
async function refresh() {
  if (!authenticated.value) return
  const values = await Promise.all([api('status'), api<Row[]>('rules'), api<string[]>('groups')])
  status.value = values[0]; rules.value = values[1]; groups.value = values[2]
  selected.value = selected.value.filter(id => rules.value.some(r => r.id === id))
  if (page.value === '备份') backups.value = await api('backups')
  if (page.value.endsWith('日志')) logs.value = await api(`logs/${page.value === '运行日志' ? 'realm' : 'operations'}?lines=${lineCount.value}`)
  if (page.value === '设置') { settings.value = await api('settings'); whitelist.value = settings.value.whitelist.join('\n') }
}
async function login() { await action(async () => { const result = await api('auth/login', 'POST', { username: username.value, password: password.value }); setCsrf(result.csrf); password.value = ''; authenticated.value = true }, '登录成功') }
function edit(row?: Row) { editingId.value = row?.id ?? null; const defaults: Row = { name: '', group: '默认', enabled: true, listen_host: '0.0.0.0', listen_port: 30000, remote_host: '', remote_port: 443, protocol: 'tcp_udp', through: '', interface: '', tcp_timeout: null, udp_timeout: null, tcp_keepalive: null, remark: '' }; editor.value = row ? Object.fromEntries(Object.keys(defaults).map(k => [k, row[k]])) : defaults }
async function saveRule(rule: Row) { await action(async () => { await api(editingId.value ? `rules/${editingId.value}` : 'rules', editingId.value ? 'PUT' : 'POST', rule); editor.value = null }, '转发规则已保存并生效') }
async function remove(row: Row) { if (confirm(`确认删除 ${row.name}？\n${row.listen_host}:${row.listen_port} → ${row.remote_host}:${row.remote_port}`)) await action(async () => { await api(`rules/${row.id}`, 'DELETE') }, '转发规则已删除') }
async function batch(which: string) { if (which === 'delete' && !confirm(`确认删除选中的 ${selected.value.length} 条规则？`)) return; await action(async () => { await api('batch', 'POST', { ids: selected.value, action: which, group: batchGroup.value }) }, '批量操作已生效') }
async function parseImport() { await action(async () => { preview.value = await api('import/preview', 'POST', { content: content.value, kind: kind.value }) }, '解析完成，请检查预览后确认导入') }
async function fileChange(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; kind.value = file.name.endsWith('.csv') ? 'csv' : 'json'; content.value = await file.text(); preview.value = null }
async function applyImport() { await action(async () => { const result = await api('import/apply', 'POST', { token: preview.value?.token, strategy: strategy.value }); preview.value = null; content.value = ''; notify(`已导入 ${result.imported} 条规则`) }, '导入完成，配置已生效') }
function exportUrl(format: string, selectedOnly = false) { return base + `export/${format}` + (selectedOnly ? '?ids=' + selected.value.join(',') : groupFilter.value ? '?group=' + encodeURIComponent(groupFilter.value) : '') }
async function saveSettings() { await action(async () => { const body = { network: settings.value.network, retention: Number(settings.value.retention), whitelist: whitelist.value.split('\n').map(v => v.trim()).filter(Boolean), confirm_lockout: false }; try { await api('settings', 'PUT', body) } catch (e) { if (String(e).includes('不包含当前客户端') && confirm('警告：白名单将阻止您访问此面板。仍然继续？')) await api('settings', 'PUT', { ...body, confirm_lockout: true }); else throw e } }, '设置已保存') }
async function changeCredentials() { if (newPassword.value !== confirmPassword.value) return notify('两次输入的新密码不一致', true); await action(async () => { await api('credentials', 'PUT', { username: username.value, current_password: currentPassword.value, password: newPassword.value }); authenticated.value = false; currentPassword.value = ''; newPassword.value = ''; confirmPassword.value = '' }, '账号已更新，请重新登录') }
async function changePath() { if (!confirm('修改后旧地址将立即失效，是否继续？')) return; await action(async () => { const r = await api('reset-path', 'POST'); location.assign(r.path) }) }
async function changeGroup(name: string, mode: string) { const next = mode === 'rename' ? prompt('新的分组名称', name) : name; if (!next || (mode === 'delete' && !confirm('删除分组后，规则将移动到默认分组。继续？'))) return; await action(async () => { await api('groups', 'POST', { name: next, old: mode === 'rename' ? name : null, delete: mode === 'delete' }); groupName.value = '' }) }
function filtered() { return rules.value.filter(r => (!groupFilter.value || r.group === groupFilter.value) && JSON.stringify(r).toLowerCase().includes(query.value.toLowerCase())) }
function date(value: number) { return new Date(value * 1000).toLocaleString('zh-CN') }
onMounted(async () => { try { const r = await api('auth/me'); setCsrf(r.csrf); username.value = r.username; authenticated.value = true; await refresh() } catch {} finally { ready.value = true } timer = setInterval(() => { if (authenticated.value && ((page.value.endsWith('日志') && autoRefresh.value) || page.value === '概览' || page.value === '系统状态')) refresh().catch(() => {}) }, 15000) })
onUnmounted(() => { clearInterval(timer); clearTimeout(toastTimer); window.removeEventListener('rmp-session-expired', sessionExpired) })
</script>
<template>
<div v-if="!ready" class="loading">正在加载…</div>
<div v-else-if="!authenticated" class="login"><form class="login-card" @submit.prevent="login"><div class="brand-icon"><Command :size="28" /></div><p class="eyebrow">YOUR NETWORK, SIMPLIFIED</p><h1>RealmPanel</h1><p class="muted">让每一次连接，都井然有序。</p><label>管理员账号<input v-model="username" autocomplete="username" required></label><label>密码<input v-model="password" type="password" autocomplete="current-password" required></label><button class="primary" :disabled="busy">{{ busy ? '正在登录…' : '登录管理面板' }}</button><small>Realm v2.9.3 · TCP / UDP 转发管理</small></form></div>
<div v-else class="shell"><aside :class="{ open: mobile }"><a class="brand" @click="page = '概览'"><span class="brand-icon"><Command :size="22" /></span><span>RealmPanel<small>NETWORK WORKSPACE</small></span></a><div class="workspace"><span class="dot"></span>个人服务器<span class="tag">LOCAL</span></div><p class="nav-label">工作空间</p><nav><button v-for="p in pages" :key="p.name" :class="{ active: page === p.name }" @click="page = p.name"><component :is="p.icon" :size="18" />{{ p.name }}<span v-if="p.name === '转发规则'" class="nav-count">{{ rules.length }}</span></button></nav><div class="sidebar-bottom"><ShieldCheck :size="18" /><div>配置安全应用<small>自动备份 · 失败回滚</small></div></div><button class="account" @click="action(async () => { await api('auth/logout', 'POST'); authenticated = false }, '已退出登录')"><span class="avatar">{{ username.slice(0, 1).toUpperCase() }}</span><span>{{ username }}<small>管理员</small></span><LogOut :size="16" /></button></aside>
<main><div class="topbar"><button aria-label="打开导航" class="mobile-menu ghost" @click="mobile = !mobile"><Menu :size="20" /></button><span class="breadcrumb"><span class="crumb-root">工作空间 <span class="slash">/</span></span>{{ page }}</span><div class="top-right"><button class="ghost" aria-label="切换黑白主题" title="切换黑白主题" @click="toggleTheme"><Sun v-if="theme === 'dark'" :size="17"/><Moon v-else :size="17"/></button><span v-if="busy" class="muted">正在应用配置…</span><span v-else class="health" :class="{ unhealthy: !status.healthy }"><span class="dot"></span>{{ status.healthy ? '系统运行正常' : '核心状态异常' }}</span><button class="ghost" title="刷新" @click="refresh().catch(showError)"><RefreshCw :size="16" /></button></div></div>
<div class="content"><header class="page-heading"><div><p class="eyebrow">{{ page === '概览' ? 'NETWORK OVERVIEW' : 'REALMPANEL WORKSPACE' }}</p><h1>{{ page }}</h1><p class="muted">{{ page === '概览' ? '连接的每个细节，尽在掌握。' : page === '转发规则' ? '管理连接、调整线路，即时安全生效。' : '在这里管理您的转发工作空间。' }}</p></div><button v-if="['概览', '转发规则'].includes(page)" class="primary" @click="edit()"><Plus :size="17" />新建转发</button></header>
<template v-if="page === '概览'"><div class="stats"><section class="stat"><span>转发规则</span><strong>{{ status.rules ?? 0 }}<small>条</small></strong><p>所有已配置的连接</p></section><section class="stat"><span>已启用</span><strong class="green">{{ status.enabled ?? 0 }}<small>条</small></strong><p><span class="dot"></span> 正在为您转发</p></section><section class="stat"><span>已暂停</span><strong>{{ (status.rules || 0) - (status.enabled || 0) }}<small>条</small></strong><p>随时可以恢复</p></section><section class="stat"><span>核心内存</span><strong>{{ status.memory_mb ?? '—' }}<small>MB</small></strong><p>轻量运行，专注连接</p></section></div><section class="core-card"><div class="core-mark"><ArrowLeftRight :size="30" /></div><div><h2>Realm Core <span class="tag">v2.9.3</span></h2><p class="muted">{{ status.healthy ? '核心服务正常，转发配置已同步。' : '核心检查异常，请查看运行日志。' }}</p></div><div class="core-meta"><span>运行时间<strong>{{ Math.floor((status.uptime || 0) / 3600) }} 小时 {{ Math.floor((status.uptime || 0) % 3600 / 60) }} 分钟</strong></span><span>监听端点<strong>{{ status.listeners?.length || 0 }} 个</strong></span></div></section><section class="panel"><header><h2>转发规则 <span class="muted">{{ rules.length }}</span></h2><button class="ghost blue" @click="page = '转发规则'">查看全部 →</button></header><div v-if="!rules.length" class="empty"><ArrowLeftRight :size="36" /><h3>从第一条连接开始</h3><p>添加 TCP、UDP 或双协议转发规则。</p><button @click="edit()">创建转发规则</button></div><div v-for="r in rules.slice(0, 6)" :key="r.id" class="rule-summary"><span class="dot" :class="{ paused: !r.enabled }"></span><strong>{{ r.name }}</strong><code>{{ r.listen_host }}:{{ r.listen_port }} <span class="muted">→</span> {{ r.remote_host }}:{{ r.remote_port }}</code><span class="protocol">{{ r.protocol.replace('_', '+').toUpperCase() }}</span></div></section><div class="hint"><ShieldCheck :size="20" /><p>放心调整每一条线路。<span>每次应用前自动备份，异常时自动恢复上一次配置。</span></p></div></template>
<template v-if="page === '转发规则' || page === '批量操作'"><section class="panel"><div class="toolbar"><div class="search"><Search :size="17" /><input v-model="query" placeholder="搜索名称、端口或目标地址"></div><select v-model="groupFilter"><option value="">全部分组</option><option v-for="g in groups" :key="g">{{ g }}</option></select></div><div class="batchbar" v-if="selected.length"><span>已选 {{ selected.length }} 条</span><button @click="batch('enable')" :disabled="busy">启动</button><button @click="batch('disable')" :disabled="busy">暂停</button><button class="danger" @click="batch('delete')" :disabled="busy">删除</button><select v-model="batchGroup"><option v-for="g in groups" :key="g">{{ g }}</option></select><button @click="batch('group')" :disabled="busy">移动分组</button><a :href="exportUrl('json', true)">导出选中</a></div><div class="tablewrap"><table><thead><tr><th><input type="checkbox" :checked="selected.length === filtered().length && selected.length > 0" @change="selected = ($event.target as HTMLInputElement).checked ? filtered().map(r => r.id) : []"></th><th>状态 / 名称</th><th>本地监听</th><th>远程目标</th><th>协议</th><th>备注</th><th>操作</th></tr></thead><tbody><tr v-for="r in filtered()" :key="r.id"><td><input v-model="selected" type="checkbox" :value="r.id"></td><td><div class="rule-name"><span class="dot" :class="{ paused: !r.enabled }"></span><strong>{{ r.name }}</strong></div><small>{{ r.group }}</small></td><td><code>{{ r.listen_host }}:{{ r.listen_port }}</code></td><td><code>{{ r.remote_host }}:{{ r.remote_port }}</code></td><td><span class="protocol">{{ r.protocol.replace('_','+').toUpperCase() }}</span></td><td class="remark">{{ r.remark || '—' }}</td><td><div class="row-actions"><button @click="edit(r)">编辑</button><button :disabled="busy" @click="action(async () => { await api(`rules/${r.id}/${r.enabled ? 'disable' : 'enable'}`, 'POST') })">{{ r.enabled ? '暂停' : '启动' }}</button><button :disabled="busy" @click="action(async () => { await api(`rules/${r.id}/clone`, 'POST') })">复制</button><button class="danger" :disabled="busy" @click="remove(r)">删除</button></div></td></tr></tbody></table></div><div v-if="!filtered().length" class="empty"><h3>暂无转发规则</h3><p>创建第一条规则，或从其他服务器导入配置。</p></div></section><section class="panel"><header><h2>分组管理</h2></header><div class="pad"><div class="chips"><div class="chip" v-for="g in groups" :key="g"><span>{{ g }}</span><button v-if="g !== '默认'" class="ghost" @click="changeGroup(g, 'rename')">改名</button><button v-if="g !== '默认'" class="ghost danger" @click="changeGroup(g, 'delete')">×</button></div></div><form class="inline-form" @submit.prevent="changeGroup(groupName, 'create')"><input v-model="groupName" required placeholder="新分组名称"><button :disabled="busy">创建分组</button></form></div></section></template>
<template v-if="page === '导入 / 导出' || page === '批量操作'"><div class="two-col"><section class="panel"><header><h2>{{ page === '批量操作' ? '批量添加' : '导入配置' }}</h2></header><div class="pad"><p class="muted">先解析和预览，确认后再应用。无效规则将阻止整个导入。</p><label>输入格式<select v-model="kind" @change="preview = null"><option value="json">RealmPanel JSON</option><option value="csv">CSV（UTF-8）</option><option value="text">批量文本</option></select></label><input type="file" accept=".json,.csv" @change="fileChange"><label>配置内容<textarea v-model="content" @input="preview = null" rows="9" placeholder="批量文本：2088|1.2.3.4|443|tcp_udp|美国01"></textarea></label><button class="primary" :disabled="!content || busy" @click="parseImport">解析并预览</button></div></section><section class="panel"><header><h2>导出配置</h2></header><div class="pad"><p>迁移规则到另一台服务器。</p><p class="muted">包含转发规则、分组和全局网络设置，不包含密码、会话或管理路径。</p><label>导出范围<select v-model="groupFilter"><option value="">全部规则</option><option v-for="g in groups" :key="g">{{ g }}</option></select></label><div class="buttons"><a class="button" :href="exportUrl('json')">下载 JSON</a><a class="button" :href="exportUrl('csv')">下载 CSV</a></div><p class="notice">CSV 使用 UTF-8 BOM，适合在 Excel 中编辑中文内容。</p></div></section></div><section v-if="preview" class="panel"><header><h2>导入预览</h2><span>共 {{ preview.total }} 条 · 新增 {{ preview.new }} · 冲突 {{ preview.conflicts.length }} · 无效 {{ preview.errors.length }}</span></header><div class="pad"><p v-for="e in preview.errors" :key="e.row" class="notice danger">第 {{ e.row }} 条：{{ e.error }}</p><p v-for="c in preview.conflicts" :key="c.row" class="notice">第 {{ c.row }} 条，端口 {{ c.port }} 与已有规则冲突。</p><label>冲突处理<select v-model="strategy"><option value="skip">跳过冲突规则</option><option value="overwrite">覆盖现有规则</option><option value="new_port">自动寻找新端口</option></select></label><p class="muted">JSON 中的全局网络参数也将应用到当前服务器。</p><button class="primary" :disabled="busy || preview.errors.length > 0" @click="applyImport">确认导入并应用</button><details><summary>查看规则详情</summary><pre>{{ JSON.stringify(preview.rules, null, 2) }}</pre></details></div></section></template>
<template v-if="page === '备份'"><section class="panel"><header><div><h2>自动保护每一次更改</h2><p class="muted">备份已加密。Web 恢复转发规则与网络参数，保留当前账号及管理地址。</p></div><button class="primary" :disabled="busy" @click="action(async () => { await api('backups', 'POST') }, '备份已创建')">创建备份</button></header><div class="tablewrap"><table><thead><tr><th>时间</th><th>原因</th><th>规则</th><th>大小</th><th>操作</th></tr></thead><tbody><tr v-for="b in backups" :key="b.id"><td>{{ date(b.time) }}</td><td>{{ b.reason }}</td><td>{{ b.rules }}</td><td>{{ (b.size / 1024).toFixed(1) }} KB</td><td class="row-actions"><a :href="base + `backups/${b.id}/download`">下载</a><button :disabled="busy" @click="confirm('确认恢复此备份？当前状态会先自动备份。') && action(async () => { await api(`backups/${b.id}/restore`, 'POST') }, '备份已恢复')">恢复</button><button class="danger" :disabled="busy" @click="confirm('确认删除此备份？') && action(async () => { await api(`backups/${b.id}`, 'DELETE') })">删除</button></td></tr></tbody></table></div></section></template>
<section v-if="page.endsWith('日志')" class="panel"><header><h2>{{ page }}</h2><div class="buttons"><select v-model.number="lineCount"><option :value="100">最近 100 行</option><option :value="500">最近 500 行</option><option :value="1000">最近 1000 行</option></select><label class="check"><input v-model="autoRefresh" type="checkbox">自动刷新</label></div></header><pre class="logs" v-if="page === '运行日志'">{{ logs.join('\n') || '暂无日志' }}</pre><div class="tablewrap" v-else><table><thead><tr><th>时间</th><th>账号 / IP</th><th>操作</th><th>结果</th></tr></thead><tbody><tr v-for="l in logs" :key="l.id"><td>{{ date(l.time) }}</td><td>{{ l.admin }}<small>{{ l.source_ip }}</small></td><td>{{ l.action }}</td><td>{{ l.result }}</td></tr></tbody></table></div></section>
<section v-if="page === '系统状态'" class="panel"><header><h2>运行状态</h2><span class="tag">每 15 秒更新</span></header><div class="pad"><div class="setting-row" v-for="(v, k) in status" :key="k"><span>{{ k }}</span><code>{{ typeof v === 'object' ? JSON.stringify(v) : v }}</code></div></div></section>
<template v-if="page === '设置'"><div class="two-col"><section class="panel"><header><h2>网络与访问</h2></header><form class="pad" @submit.prevent="saveSettings"><label v-for="key in ['tcp_timeout','udp_timeout','tcp_keepalive']" :key="key">{{ key }}（秒）<input v-model.number="settings.network[key]" type="number" min="0" required></label><label>备份保留数量<select v-model.number="settings.retention"><option v-for="n in [10,20,30,50,100]" :key="n" :value="n">{{ n }} 份</option></select></label><label>IP 白名单（每行一个 IP/CIDR，留空关闭）<textarea v-model="whitelist" rows="4"></textarea></label><p class="muted">当前客户端：{{ settings.client_ip }}</p><button class="primary" :disabled="busy">保存并应用</button></form></section><div><section class="panel"><header><h2>管理员账号</h2></header><form class="pad" @submit.prevent="changeCredentials"><label>账号<input v-model="username" required></label><label>当前密码<input v-model="currentPassword" type="password" required autocomplete="current-password"></label><label>新密码<input v-model="newPassword" type="password" minlength="8" required autocomplete="new-password"></label><label>确认新密码<input v-model="confirmPassword" type="password" minlength="8" required autocomplete="new-password"></label><button :disabled="busy">更新账号与密码</button></form></section><section class="panel"><header><h2>偏好与版本</h2></header><div class="pad"><label>外观<select v-model="theme"><option value="system">跟随系统</option><option value="light">亮色</option><option value="dark">暗色</option></select></label><p>RealmPanel 0.9.2 · Realm Core 2.9.3</p><p class="muted">通过 SSH 使用 rmpctl update 更新。</p><button :disabled="busy" @click="changePath">重新生成管理路径</button></div></section></div></div></template>
<footer class="page-footer"><span>RealmPanel</span><span>轻量、可靠、井然有序。</span><span>v0.9.2</span></footer></div></main></div>
<RuleEditor v-if="editor" :rule="editor" :groups="groups" :busy="busy" @close="editor = null" @save="saveRule" />
<div v-if="toast" class="toast" :class="{ error }" role="status">{{ toast }}</div>
</template>
