<script setup lang="ts">
import { ref } from 'vue'
import { api } from './api'
const props = defineProps<{ rule: Record<string, any>, groups: string[], busy: boolean }>()
const emit = defineEmits<{ close: [], save: [rule: Record<string, any>] }>()
const form = ref({ ...props.rule })
const result = ref('')
async function test(which: string) { try { result.value = '正在检测…'; result.value = (await api(which, 'POST', form.value)).detail } catch (e) { result.value = String(e) } }
</script>
<template><div class="overlay" @click.self="emit('close')"><section class="modal"><header><div><p class="eyebrow">FORWARDING RULE</p><h2>{{ rule.name ? '编辑转发规则' : '新建转发规则' }}</h2></div><button class="ghost" @click="emit('close')">关闭</button></header><form @submit.prevent="emit('save', form)"><div class="formgrid"><label>名称<input v-model="form.name" required maxlength="100" placeholder="例如：美国线路 01"></label><label>分组<select v-model="form.group"><option v-for="g in groups" :key="g">{{ g }}</option></select></label><label>监听地址<input v-model="form.listen_host" required></label><label>监听端口<input v-model.number="form.listen_port" type="number" min="1" max="65535" required></label><label>目标地址<input v-model="form.remote_host" required placeholder="IPv4、IPv6 或域名"></label><label>目标端口<input v-model.number="form.remote_port" type="number" min="1" max="65535" required></label></div><label>转发协议<select v-model="form.protocol"><option value="tcp_udp">TCP + UDP</option><option value="tcp">TCP</option><option value="udp">UDP</option></select></label><label class="check"><input v-model="form.enabled" type="checkbox">立即启用此规则</label><label>备注<textarea v-model="form.remark" rows="2" maxlength="2000"></textarea></label><details><summary>高级设置</summary><div class="formgrid"><label>出口源 IP（Through）<input v-model="form.through"></label><label>出口网卡（Interface）<input v-model="form.interface"></label><label v-for="key in ['tcp_timeout','udp_timeout','tcp_keepalive']" :key="key">{{ key }}<input :value="form[key]" @input="form[key] = ($event.target as HTMLInputElement).value === '' ? null : Number(($event.target as HTMLInputElement).value)" type="number" min="0" placeholder="使用全局默认值"></label></div></details><p class="muted">即时应用会安全重启 Realm，现有连接可能短暂中断。</p><p v-if="result" class="notice">{{ result }}</p><footer><button type="button" @click="test('check-port')">检测端口</button><button type="button" @click="test('test-target')">测试目标</button><button class="primary" :disabled="busy">{{ busy ? '正在应用…' : '保存并应用' }}</button></footer></form></section></div></template>
